/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.doat.main;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.IOException;
import java.nio.charset.Charset;
import java.util.ArrayList;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import nl.siegmann.epublib.domain.TOCReference;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Administrator
 */
public class EditChapDialog extends java.awt.Dialog {

    private String title, content;
    private TOCReference toc = null;
    private boolean isChange = false,isDelete=false;
    private int pos = 0;
    private ArrayList<String[]> list_chap = new ArrayList<>();

    /**
     * Creates new form EditChapDialog
     */
    public EditChapDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pan_find_replace.setVisible(false);
        this.pack();
    }

    public void setData(TOCReference toc) {
        try {
            this.toc = toc;
            title = toc.getTitle();
            content = new String(toc.getResource().getData(), "UTF-8");
            txt_chap_name.setText(title);
            txt_chap_content.setContentType("text/html");
            txt_chap_content.setText(content);
            txt_chap_content.setCaretPosition(0);
            txt_chap_content.getDocument().addDocumentListener(new MyDocumentListener());
            txt_chap_content.addFocusListener(new ClearTextPrompt("content"));
            txt_chap_name.getDocument().addDocumentListener(new MyDocumentListener());
            txt_chap_name.addFocusListener(new ClearTextPrompt("title"));
            content = txt_chap_content.getText();
            String[] chap_source = new String[]{title, content};
            list_chap.add(chap_source);
        } catch (IOException ex) {
            showErrorMess("Lỗi Đọc Chương");
        }

    }

    private void refectView() {
        txt_chap_name.setText(title);
        txt_chap_content.setText(content);
        txt_chap_content.setCaretPosition(0);
    }

    private void saveData() {
        isChange = false;
        String c_title, c_content;
        try {
            c_title = txt_chap_name.getText();
        } catch (NullPointerException e) {
            c_title = "No Name";
        }
        try {
            c_content = txt_chap_content.getText();
        } catch (NullPointerException e) {
            c_content = " ";
        }
        toc.setTitle(c_title);
        toc.getResource().setData(c_content.getBytes(Charset.forName("utf-8")));
    }

    public TOCReference getData() {
        return toc;
    }
    public boolean isDelete(){
        return this.isDelete;
    }
    public void showErrorMess(String error) {
        JOptionPane.showMessageDialog(this, error, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    public void showMess(String mess) {
        JOptionPane.showMessageDialog(this, mess, "Thông tin", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_undo = new javax.swing.JButton();
        btn_redo = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        txt_chap_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_chap_content = new javax.swing.JEditorPane();
        txt_find = new javax.swing.JButton();
        pan_find_replace = new javax.swing.JPanel();
        txt_find_text = new javax.swing.JTextField();
        txt_replace_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_repalce_all = new javax.swing.JButton();
        ch_find_title = new javax.swing.JCheckBox();
        btn_delete = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btn_undo.setText("Undo");
        btn_undo.setEnabled(false);
        btn_undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_undoActionPerformed(evt);
            }
        });

        btn_redo.setText("Redo");
        btn_redo.setEnabled(false);
        btn_redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redoActionPerformed(evt);
            }
        });

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txt_chap_content);

        txt_find.setText("Find N Replace");
        txt_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_findActionPerformed(evt);
            }
        });

        jLabel1.setText("Find");

        jLabel2.setText("Replace");

        btn_repalce_all.setText("Replace All");
        btn_repalce_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_repalce_allActionPerformed(evt);
            }
        });

        ch_find_title.setText("Include Title");

        javax.swing.GroupLayout pan_find_replaceLayout = new javax.swing.GroupLayout(pan_find_replace);
        pan_find_replace.setLayout(pan_find_replaceLayout);
        pan_find_replaceLayout.setHorizontalGroup(
            pan_find_replaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_find_replaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_find_replaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_find_replaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_find_text)
                    .addComponent(txt_replace_text, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pan_find_replaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_repalce_all)
                    .addComponent(ch_find_title))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_find_replaceLayout.setVerticalGroup(
            pan_find_replaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_find_replaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_find_replaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_find_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_repalce_all))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_find_replaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_replace_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ch_find_title))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_delete.setForeground(new java.awt.Color(255, 0, 51));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(pan_find_replace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_chap_name, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_undo)
                .addGap(18, 18, 18)
                .addComponent(btn_redo)
                .addGap(18, 18, 18)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_find)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_undo)
                    .addComponent(btn_redo)
                    .addComponent(btn_save)
                    .addComponent(txt_find)
                    .addComponent(btn_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_find_replace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txt_chap_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog

        if (isChange) {
            int input = JOptionPane.showConfirmDialog(this, "Lưu Sửa Đổi", "Cảnh Báo", JOptionPane.YES_NO_CANCEL_OPTION);
            switch (input) {
                case 0: {
                    saveData();
                    break;
                }
                case 1: {
                    setVisible(false);
                    dispose();
                    return;
                }
                case 2: {
                    return;
                }
            }
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        saveData();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_findActionPerformed
        // TODO add your handling code here:
        if (pan_find_replace.isVisible()) {
            pan_find_replace.setVisible(false);
        } else {
            pan_find_replace.setVisible(true);
        }
        this.pack();
    }//GEN-LAST:event_txt_findActionPerformed

    private void btn_undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_undoActionPerformed
        // TODO add your handling code here:
        if (pos > 0) {
            String[] c = list_chap.get(pos - 1);
            title = c[0];
            content = c[1];
            refectView();
            btn_redo.setEnabled(true);
            pos--;
            if (pos == 0) {
                btn_undo.setEnabled(false);
            }
        }

    }//GEN-LAST:event_btn_undoActionPerformed

    private void btn_redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redoActionPerformed
        // TODO add your handling code here:
        if (pos <= list_chap.size() - 2) {
            String[] c = list_chap.get(pos + 1);
            title = c[0];
            content = c[1];
            refectView();
            btn_undo.setEnabled(true);
            pos++;
            if (pos == (list_chap.size() - 1)) {
                btn_redo.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btn_redoActionPerformed

    private void btn_repalce_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_repalce_allActionPerformed
        // TODO add your handling code here:
        String find = null, replace = "";
        try {
            find = txt_find_text.getText();
        } catch (NullPointerException e) {
            find = null;
        }
        try {
            replace = txt_replace_text.getText();
        } catch (NullPointerException e) {
            replace = "";
        }
        if (find != null) {
            content = content.replaceAll(find, replace);
            if (ch_find_title.isSelected()) {
                title = title.replaceAll(find, replace);
            }
            refectView();
        }
        System.out.println("null");
    }//GEN-LAST:event_btn_repalce_allActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Xóa Vĩnh Viễn Chương Này", "Cảnh Báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        switch (res) {
            case 0: {
                isDelete=true;
                break;
            }
            case 1: {
                return;
            }
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditChapDialog dialog = new EditChapDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    class MyDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            isChange = true;
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            isChange = true;
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            isChange = true;
        }

    }

    public class ClearTextPrompt extends FocusAdapter {

        private String prompt;

        public ClearTextPrompt(String prompt) {
            this.prompt = prompt;
        }

        @Override
        public void focusLost(FocusEvent e) {
            String s;
            try {
                switch (prompt) {
                    case "title": {
                        JTextField t = (JTextField) e.getSource();
                        s = t.getText();
                        if (!s.equals(title)) {
                            title = s;
                            list_chap.add(new String[]{s, content});
                            pos++;
                            btn_undo.setEnabled(true);
                            System.out.println("has change title");
                        }
                        break;
                    }
                    case "content": {
                        JEditorPane t = (JEditorPane) e.getSource();
                        s = t.getText();
                        if (!s.equals(content)) {
                            content = s;
                            list_chap.add(new String[]{title, s});
                            pos++;
                            btn_undo.setEnabled(true);
                            System.out.println("has change content");

                        }
                        break;
                    }
                }

            } catch (NullPointerException ex) {
                return;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_redo;
    private javax.swing.JButton btn_repalce_all;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_undo;
    private javax.swing.JCheckBox ch_find_title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pan_find_replace;
    private javax.swing.JEditorPane txt_chap_content;
    private javax.swing.JTextField txt_chap_name;
    private javax.swing.JButton txt_find;
    private javax.swing.JTextField txt_find_text;
    private javax.swing.JTextField txt_replace_text;
    // End of variables declaration//GEN-END:variables
}
